# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'pim/kmime': '@latest'
    'pim/kimap2': '@same'
    'pim/kdav2': '@same'
    'frameworks/kcontacts': '@latest'
    'frameworks/kcalendarcore': '@latest'
    'libraries/kasync': '@same'
