# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kcontacts': '@latest'
    'frameworks/kcalendarcore': '@latest'
    'pim/kimap2' : '@latest'
    'pim/kdav2' : '@latest'
    'pim/mimetreeparser' : '@latest'
    'libraries/kasync' : '@latest'

Options:
  require-passing-tests-on: [ 'Linux/Qt5']
